apiVersion: v1
kind: Pod
metadata:
 name: imageclassificationapp
spec:
 containers:
   - name: model-api
     image: sivak8s.azurecr.io/model-api:$(Build.BuildId)
     ports:
       - containerPort: 88
