apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    name: api
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 88
    targetPort: 88
  selector:
    name: ai-api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  ai-api-deploy
  labels:
    name:  ai-api
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  ai-api
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - image: sivak8s.azurecr.io/model-api
        name:  ai-api-cntnr
        resources:
          requests:
            cpu: "20m"
            memory: "55M"

